version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
    volumes:
      - .:/app
    env_file: .env
  db:
    image: postgres:14.1
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - ${PGPORT}
    ports:
      - "${PGPORT}:${PGPORT}"
    command: -p ${PGPORT}
volumes:
  pgdata:
